name: 'Healthcare_360'
version: '1.0.0'
config-version: 2

# This profile should match the connection name in your profiles.yml file
profile: 'health360_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory compiled SQL files go to
clean-targets:         # directories removed by 'dbt clean'
  - "target"
  - "dabs"
  - "logs"

models:
  Healthcare_360:  # Matches the 'name' defined at the top of dbt_project.yml
    example:
      staging:
        +schema: STAGING
        +materialized: table
      marts:
        +materialized: table